name: 2 Microservice App Deploy - GitOps

on: 
  workflow_dispatch:
    inputs:
      ACRNAME:
        description: 'The Name of the ACR resource'
        required: true
        type: string
      ENVIRONMENT:
        description: 'A GitHub Environment to pull action secrets from'
        required: true
        type: environment

permissions:
  id-token: write
  contents: write
  pull-requests: write
  actions: write

jobs:
  BuildPush:
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}
    steps:
      - name: Get application code from repo
        uses: actions/checkout@v2
      
      - name: Log into Azure subscription
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
      
      - name: Connect to Azure Container Registry (ACR)
        id: acrconnect
        run: |
          echo "Retrieving access token from ${{ inputs.ACRNAME }}"
          TOKEN=$(az acr login -n ${{ inputs.ACRNAME }} --expose-token)

          if [ -z "$TOKEN" ]; 
          then
            echo "ACR Token was not retrieved successfully"
            exit 1
          fi

          ACRTOKEN=$(echo $TOKEN | jq -r ".accessToken")
          LOGINSERVER=$(echo $TOKEN | jq -r ".loginServer")

          echo "ACR Login Server: $LOGINSERVER"
          echo "::set-output name=loginServer::$LOGINSERVER"

          echo "Passing token as stdin to docker login"
          echo $ACRTOKEN | docker login $LOGINSERVER -u 00000000-0000-0000-0000-000000000000 --password-stdin

      - name: Build and push order-service image
        run: |
          cd workloads/src/order-service
          docker build . -t ${{ inputs.ACRNAME }}.azurecr.io/order-service:${{ github.run_number }}
          docker push ${{ inputs.ACRNAME }}.azurecr.io/order-service:${{ github.run_number }}

      - name: Build and push product-service image
        run: |
          cd workloads/src/product-service
          docker build . -t ${{ inputs.ACRNAME }}.azurecr.io/product-service:${{ github.run_number }}
          docker push ${{ inputs.ACRNAME }}.azurecr.io/product-service:${{ github.run_number }}

      - name: Build and push store-front image
        run: |
          cd workloads/src/store-front
          docker build . -t ${{ inputs.ACRNAME }}.azurecr.io/store-front:${{ github.run_number }}
          docker push ${{ inputs.ACRNAME }}.azurecr.io/store-front:${{ github.run_number }}

      - name: Build and push adservice image
        run: |
          cd workloads/src2/adservice
          docker build . -t ${{ inputs.ACRNAME }}.azurecr.io/adservice:${{ github.run_number }}
          docker push ${{ inputs.ACRNAME }}.azurecr.io/adservice:${{ github.run_number }}
      
      - name: Build and push cartservice image
        run: |
          cd workloads/src2/cartservice
          docker build . -t ${{ inputs.ACRNAME }}.azurecr.io/cartservice:${{ github.run_number }}
          docker push ${{ inputs.ACRNAME }}.azurecr.io/cartservice:${{ github.run_number }}

        - name: Build and push checkoutservice image
        run: |
          cd workloads/src2/checkoutservice
          docker build . -t ${{ inputs.ACRNAME }}.azurecr.io/checkoutservice:${{ github.run_number }}
          docker push ${{ inputs.ACRNAME }}.azurecr.io/checkoutservice:${{ github.run_number }}

      - name: Build and push currencyservice image
        run: |
          cd workloads/src2/currencyservice
          docker build . -t ${{ inputs.ACRNAME }}.azurecr.io/currencyservice:${{ github.run_number }}
          docker push ${{ inputs.ACRNAME }}.azurecr.io/currencyservice:${{ github.run_number }}

      - name: Build and push emailservice image
        run: |
          cd workloads/src2/emailservice
          docker build . -t ${{ inputs.ACRNAME }}.azurecr.io/emailservice:${{ github.run_number }}
          docker push ${{ inputs.ACRNAME }}.azurecr.io/emailservice:${{ github.run_number }}

      - name: Build and push frontend image
        run: |
          cd workloads/src2/frontend
          docker build . -t ${{ inputs.ACRNAME }}.azurecr.io/frontend:${{ github.run_number }}
          docker push ${{ inputs.ACRNAME }}.azurecr.io/frontend:${{ github.run_number }}
      
      - name: Build and push loadgenerator image
        run: |
          cd workloads/src2/loadgenerator
          docker build . -t ${{ inputs.ACRNAME }}.azurecr.io/loadgenerator:${{ github.run_number }}
          docker push ${{ inputs.ACRNAME }}.azurecr.io/loadgenerator:${{ github.run_number }}

      - name: Build and push paymentservice image
        run: |
          cd workloads/src2/paymentservice
          docker build . -t ${{ inputs.ACRNAME }}.azurecr.io/paymentservice:${{ github.run_number }}
          docker push ${{ inputs.ACRNAME }}.azurecr.io/paymentservice:${{ github.run_number }}

      - name: Build and push productcatalogservice image
        run: |
          cd workloads/src2/productcatalogservice
          docker build . -t ${{ inputs.ACRNAME }}.azurecr.io/productcatalogservice:${{ github.run_number }}
          docker push ${{ inputs.ACRNAME }}.azurecr.io/productcatalogservice:${{ github.run_number }}

      - name: Build and push recommendationservice image
        run: |
          cd workloads/src2/recommendationservice
          docker build . -t ${{ inputs.ACRNAME }}.azurecr.io/recommendationservice:${{ github.run_number }}
          docker push ${{ inputs.ACRNAME }}.azurecr.io/recommendationservice:${{ github.run_number }}

      - name: Build and push shippingserivce image
        run: |
          cd workloads/src2/shippingservice
          docker build . -t ${{ inputs.ACRNAME }}.azurecr.io/shippingservice:${{ github.run_number }}
          docker push ${{ inputs.ACRNAME }}.azurecr.io/shippingservice:${{ github.run_number }}
      
      - name: Pull and push redis image
        run: |
          docker pull redis:alpine
          docker tag redis:alpine ${{ inputs.ACRNAME }}.azurecr.io/redis:alpine
          docker push ${{ inputs.ACRNAME }}.azurecr.io/redis:alpine

      - name: Pull and push rabbitmq image
        run: |
          docker pull rabbitmq:3.11.17-management-alpine
          docker tag rabbitmq:3.11.17-management-alpine ${{ inputs.ACRNAME }}.azurecr.io/rabbitmq:3.11.17-management-alpine
          docker push ${{ inputs.ACRNAME }}.azurecr.io/rabbitmq:3.11.17-management-alpine

  Update-K8s-Manifests:
    name: Update K8s Deployment Manifest with Image Version
    needs: BuildPush
    environment: ${{ inputs.ENVIRONMENT }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update image name in manifest file
        uses: azure/powershell@v1
        with:
          inlineScript: |
            $line1 = Get-Content workloads/src/order-service.deployment.yaml | Select-String image: | Select-Object -ExpandProperty Line
            $line2 = Get-Content workloads/src/product-service.deployment.yaml | Select-String image: | Select-Object -ExpandProperty Line
            $line3 = Get-Content workloads/src/store-front.deployment.yaml | Select-String image: | Select-Object -ExpandProperty Line
            $line4 = Get-Content workloads/src/rabbitmq.yaml | Select-String image: | Select-Object -ExpandProperty Line

            $line5 = Get-Content workloads/src2/adservice.deployment.yaml | Select-String image: | Select-Object -ExpandProperty Line
            $line6 = Get-Content workloads/src2/cartservice.deployment.yaml | Select-String image: | Select-Object -ExpandProperty Line
            $line7 = Get-Content workloads/src2/checkout.deployment.yaml | Select-String image: | Select-Object -ExpandProperty Line
            $line8 = Get-Content workloads/src2/currencyservice.yaml | Select-String image: | Select-Object -ExpandProperty Line

            $line9 = Get-Content workloads/src2/emailservice.deployment.yaml | Select-String image: | Select-Object -ExpandProperty Line
            $line10 = Get-Content workloads/src2/frontend.deployment.yaml | Select-String image: | Select-Object -ExpandProperty Line
            $line11 = Get-Content workloads/src2/loadgenerator.deployment.yaml | Select-String image: | Select-Object -ExpandProperty Line
            $line12 = Get-Content workloads/src2/paymentservice.yaml | Select-String image: | Select-Object -ExpandProperty Line

            $line13 = Get-Content workloads/src2/productcatalogservice.deployment.yaml | Select-String image: | Select-Object -ExpandProperty Line
            $line14 = Get-Content workloads/src2/recommendationservice.deployment.yaml | Select-String image: | Select-Object -ExpandProperty Line
            $line15 = Get-Content workloads/src2/shippingservice.deployment.yaml | Select-String image: | Select-Object -ExpandProperty Line
            $line16 = Get-Content workloads/src2/rediscart.yaml | Select-String image: | Select-Object -ExpandProperty Line

            $content1 = Get-Content workloads/src/order-service.deployment.yaml
            $content1 | ForEach-Object {$_ -replace $line1,"        image: ${{ inputs.ACRNAME }}.azurecr.io/order-service:${{ github.run_number }}"} | Set-Content workloads/src/order-service.deployment.yaml

            $content2 = Get-Content workloads/src/product-service.deployment.yaml
            $content2 | ForEach-Object {$_ -replace $line2,"        image: ${{ inputs.ACRNAME }}.azurecr.io/product-service:${{ github.run_number }}"} | Set-Content workloads/src/product-service.deployment.yaml

            $content3 = Get-Content workloads/src/store-front.deployment.yaml
            $content3 | ForEach-Object {$_ -replace $line3,"        image: ${{ inputs.ACRNAME }}.azurecr.io/store-front:${{ github.run_number }}"} | Set-Content workloads/src/store-front.deployment.yaml

            $content4 = Get-Content workloads/src/rabbitmq.yaml
            $content4 | ForEach-Object {$_ -replace $line4,"        image: ${{ inputs.ACRNAME }}.azurecr.io/rabbitmq:${{ github.run_number }}"} | Set-Content workloads/src/rabbitmq.yaml

            $content5 = Get-Content workloads/src2/adservice.deployment.yaml
            $content5 | ForEach-Object {$_ -replace $line5,"        image: ${{ inputs.ACRNAME }}.azurecr.io/adservice:${{ github.run_number }}"} | Set-Content workloads/src2/adservice.deployment.yaml

            $content6 = Get-Content workloads/src2/cartservice.deployment.yaml
            $content6 | ForEach-Object {$_ -replace $line6,"        image: ${{ inputs.ACRNAME }}.azurecr.io/cartservice:${{ github.run_number }}"} | Set-Content workloads/src2/cartservice.deployment.yaml

            $content7 = Get-Content workloads/src2/checkoutservice.deployment.yaml
            $content7 | ForEach-Object {$_ -replace $line7,"        image: ${{ inputs.ACRNAME }}.azurecr.io/checkoutservice:${{ github.run_number }}"} | Set-Content workloads/src2/checkoutservice.deployment.yaml

            $content8 = Get-Content workloads/src2/currencyservice.deployment.yaml
            $content8 | ForEach-Object {$_ -replace $line8,"        image: ${{ inputs.ACRNAME }}.azurecr.io/currencyservice:${{ github.run_number }}"} | Set-Content workloads/src2/currencyservice.deployment.yaml

            $content9 = Get-Content workloads/src2/emailservice.deployment.yaml
            $content9 | ForEach-Object {$_ -replace $line9,"        image: ${{ inputs.ACRNAME }}.azurecr.io/emailservice:${{ github.run_number }}"} | Set-Content workloads/src2/emailservice.deployment.yaml

            $content10 = Get-Content workloads/src2/frontend.deployment.yaml
            $content10 | ForEach-Object {$_ -replace $line10,"        image: ${{ inputs.ACRNAME }}.azurecr.io/frontend:${{ github.run_number }}"} | Set-Content workloads/src2/frontend.deployment.yaml

            $content11 = Get-Content workloads/src2/loadgenerator.deployment.yaml
            $content11 | ForEach-Object {$_ -replace $line11,"        image: ${{ inputs.ACRNAME }}.azurecr.io/loadgenerator:${{ github.run_number }}"} | Set-Content workloads/src2/loadgenerator.deployment.yaml

            $content12 = Get-Content workloads/src2/paymentservice.deployment.yaml
            $content12 | ForEach-Object {$_ -replace $line12,"        image: ${{ inputs.ACRNAME }}.azurecr.io/paymentservice:${{ github.run_number }}"} | Set-Content workloads/src2/paymentservice.deployment.yaml

            $content13 = Get-Content workloads/src2/productcatalogservice.deployment.yaml
            $content13 | ForEach-Object {$_ -replace $line13,"        image: ${{ inputs.ACRNAME }}.azurecr.io/productcatalogservice:${{ github.run_number }}"} | Set-Content workloads/src2/productcatalogservice.deployment.yaml

            $content14 = Get-Content workloads/src2/recommendationservice.deployment.yaml
            $content14 | ForEach-Object {$_ -replace $line14,"        image: ${{ inputs.ACRNAME }}.azurecr.io/recommendationservice:${{ github.run_number }}"} | Set-Content workloads/src2/recommendationservice.deployment.yaml

            $content15 = Get-Content workloads/src2/shippingservice.deployment.yaml
            $content15 | ForEach-Object {$_ -replace $line15,"        image: ${{ inputs.ACRNAME }}.azurecr.io/shippingservice:${{ github.run_number }}"} | Set-Content workloads/src2/shippingservice.deployment.yaml

            $content16 = Get-Content workloads/src2/rediscart.deployment.yaml
            $content16 | ForEach-Object {$_ -replace $line16,"        image: ${{ inputs.ACRNAME }}.azurecr.io/redis:${{ github.run_number }}"} | Set-Content workloads/src2/rediscart.deployemnt.yaml
          azPSVersion: "latest"
    
    
      - name: Commit changes in manifest to repo
        run: | 
          git config user.name "GitHub Actions Bot"
          git config user.email ""
          git add workloads/src/order-service.deployment.yaml
          git add workloads/src/product-service.deployment.yaml
          git add workloads/src/store-front.deployment.yaml
          git add workloads/src/rabbitmq.yaml
          git add workloads/src2/adservice.deployment.yaml
          git add workloads/src2/cartservice.deployment.yaml
          git add workloads/src2/checkoutservice.deployment.yaml
          git add workloads/src2/currencyservice.deployment.yaml
          git add workloads/src2/emailservice.deployment.yaml
          git add workloads/src2/frontend.deployment.yaml
          git add workloads/src2/loadgenerator.deployment.yaml
          git add workloads/src2/paymentservice.deployment.yaml
          git add workloads/src2/productcatalogservice.deployment.yaml
          git add workloads/src2/recommendationservice.deployment.yaml
          git add workloads/src2/shippingservice.deployment.yaml
          git add workloads/src2/rediscart.deployment.yaml
          git commit -m "Update image version in K8s Deployment manifests file"
          git push origin
